### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aPaleBlueDot** [EgoDevs/ego#4]
Hi, I read on the Dfinity forum about this project, and that it was open-sourced. I didn't come across a license file, is it going to be Apache / MIT licensed?

**Comment by neeboo** [comment]
Hi, it's going to be MIT, sorry we haven't added licenses to the repo. Will add in next commit, thanks for reminding us

**Comment by aPaleBlueDot** [comment]
Thx for your prompt reply. Happy to hear about the MIT choice.

**Comment by neeboo** [comment]
License added, https://github.com/EgoDevs/ego/commit/5b3117375461e9c3516ad281101f616ebff628d0
